mate-desktop/mate-calc

configure.ac
src/math-window.c

and drop old bits
Tested with:
grep -nr GTK_CHECK_VERSION *
grep -nr GLIB_CHECK_VERSION *

building: bump required glib and gtk+ versions

---

src/math-window.c

avoid deprecated gtk_image_menu_item_new_from_stock
and set the "help-browser" icon in Help/Contents
The expected with this PR: the same icons and keyboard shortcuts like before
Without the PR:
With the PR:
I would like to avoid the extra space in the left, but, by the moment, I don't know how to do that
Note: I think this PR affects translations

avoid deprecated gtk_image_menu_item_new_from_stock

---

src/math-buttons.c

Please test.
Honestly i don't know which menu is affected exactly.
Some buttons have a left-click menu but i don't see the expected different.

replace deprecated gtk_menu_popup

---

data/buttons-advanced.ui
data/buttons-basic.ui
data/buttons-financial.ui
data/buttons-programming.ui
data/preferences.ui
src/math-buttons.c

UI: replace all deprecated elements

---

src/math-equation.c

This ensures compatibility with pasting into software that cannot handle Unicode characters (e.g. LibreOffice)
Fixes #57

Copy equation as ASCII text

---

data/buttons-financial.ui
data/buttons-programming.ui

How to test:
Click in these buttons and see the calculator icon in the title of dialogs.

ui files: add missing icons in titles to dialogs

---

src/math-display.c

Seems `gtk_widget_ensure_style` is useless, according to the documentation:
https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-ensure-style
> Not a very useful function; most of the time, if you want the style, the widget is realized, and realized widgets are guaranteed to have a style already.

math-display.c: avoid deprecated 'gtk_widget_ensure_style'

---

src/math-display.c

based in the gnome-calculator commit:
https://gitlab.gnome.org/GNOME/gnome-calculator/commit/a6e6a1d94a36950df8776e38218fe349a9818ae5

math-display: avoid deprecated 'gtk_widget_modify_bg'

---

src/math-buttons.c

Fixes cppcheck warning:
`[src/math-buttons.c:391]: (error) Shifting signed 64-bit value by 63 bits is undefined behaviour`

math-buttons: avoid shifting signed 64-bit value by 63 bits

---

src/mate-calc.c

'g_path_get_basename' needs to be freed
Fix memory leak detected by valgrind:
```
valgrind --leak-check=full mate-calc
==17452== 10 bytes in 1 blocks are definitely lost in loss record 501 of 10,243
==17452==    at 0x483577F: malloc (vg_replace_malloc.c:299)
==17452==    by 0x5657900: g_malloc (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.5800.3)
==17452==    by 0x563E84A: g_path_get_basename (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.5800.3)
==17452==    by 0x11A9E3: main (in /usr/bin/mate-calc)
```

mate-calc: Fix memory leak

---

src/mp-serializer.c

Fixes #25 and #26.
It creates an MPNumber as small as the smallest number which can be displayed in fixed notation and then compares it to the result. If the result is even smaller it switches to exponential (scientific) notation.

fixes issues 25 and 26

---

src/mp.c

Fixes https://github.com/mate-desktop/mate-calc/issues/100
based in gnome-calculator commit:
https://gitlab.gnome.org/GNOME/gnome-calculator/commit/6eb0f2b5e6df456a97a796b35d811376a69679e0

mp: Fix calculate result ln(e^(i*π))

---

src/math-buttons.c

Fixes cppcheck warning:
`[src/math-buttons.c:513] -> [src/math-buttons.c:514]: (warning) Identical inner 'return' condition is always true.`

math-buttons: Fix cppcheck warning: Identical inner 'return'

---

src/buttons-advanced.ui
src/buttons-basic.ui
src/buttons-financial.ui
src/buttons-programming.ui

If this has an effect depends on the theme. This gives the result (=) button the colour applied to the suggested-action style class by the theme. Currently has effects in Menta theme. I saw this on gnome-calculator. Partly solves #40.

buttons-ui: add style class "suggested-action" to result button

---

src/buttons-advanced.ui
src/math-buttons.c
src/mp-equation.c
src/test-mp-equation.c

This introduces some physical constants the way pi and e were introduced. To get this working correctly you have to get this patch from me as well #98, otherwise most constants will be shown as 0. The constants are clickable from a drop-down menu:

This adds some physical constants

---

src/mp-binary.c
src/parserfunc.c

Fixes #114 
Closes #115 
To test, set the calc to Programming -> Hexadecimal and type `NOT ffffffffffffffffffffffffffffffff`.
Without this commit it segfaults. With this commit it should display "Overflow: Try a bigger word size"

parserfunc: Return NULL on NOT operation overflow

---

.travis.yml
configure.ac

Fixes error in arch build:
`*** error: gettext infrastructure mismatch: using a Makefile.in.in from gettext version 0.19 but the autoconf macros are from gettext version 0.20`
The first commit is unrelated, is here just to see the error in travis of arch build.

sets the required version for gettext (0.19.8)

---

src/mp-binary.c
src/mp.h

cppcheck --enable=unusedFunction .
[src/mp-binary.c:165]: (style) The function 'mp_mask' is never used.

The function 'mp_mask' is never used

---

data/mate-calc.desktop.in

Taken from a downstream Debian patch.

mate-calc.desktop.in: Add missing Keywords.

---

data/org.mate.calc.gschema.xml
src/Makefile.am
src/history-entry.ui
src/mate-calc.c
src/math-equation.c
src/math-history-entry.c
src/math-history-entry.h
src/math-history.c
src/math-history.h
src/math-window.c
src/math-window.h
src/org.mate.calculator.gresource.xml

So this lets mate-calc as it is. It just adds the option to show the history if desired by the user (menu->View->History or ctrl+h).
- adds history view to show recent calculations.
- adds an option to enable/disable history (disabled by default).
- adds the possibility to resize mate-calc if history is enabled.
Closes #32 and closes #42 and closes #131

history-view

---

src/currency-manager.c
src/test-mp-equation.c
src/test-mp.c

```
currency-manager.c:170:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
170 | get_imf_rate_filepath()
| ^~~~~~~~~~~~~~~~~~~~~
currency-manager.c:180:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
180 | get_ecb_rate_filepath()
| ^~~~~~~~~~~~~~~~~~~~~
test-mp.c:100:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
100 | test_numbers()
| ^~~~~~~~~~~~
test-mp.c:144:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
144 | test_mp()
| ^~~~~~~
test-mp-equation.c:121:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
121 | test_conversions()
| ^~~~~~~~~~~~~~~~
test-mp-equation.c:189:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
189 | test_equations() …
```

Remove warnings: function declaration isn’t a prototype

---

help/C/functions.page
src/mp-equation.c
src/mp.c
src/mp.h
src/test-mp-equation.c

They are called with `zeta (x)` or `erf (x)` respectively and are commonly used functions in both mathematics and physics.

add Riemann zeta function and Gauss error function

---

src/math-display.c

Notification area is hidden under scrollbar currently.
Before:
After:

set bottom margin to 12 for gtk widget info_view

---

src/math-window.c

math-window: show GNU MPFR and GNU MPC version in about dialog

---

src/math-buttons.c

As it is with all other functions in order to press button and enter function argument, without having to press space bar.
This is a problem if function argument is a variable or the last answer (which internally is a variable).
Test: Press "asin" and "pi" button for example.

math-buttons: add space character after inverse trig. functions

---

src/math-history-entry.c
src/math-history-entry.h
src/math-history.c
src/math-history.h
src/math-window.c

Inspired by `gnome-calculators` implementation. If this PR gets merged, it would make #139 obsolete. If you want, I can change the "Clear History" shortcut and menu item, I took Shift+Ctrl+C for now.
EDIT: Just noticed that Shift+Ctrl+C may be a bad idea, because some are used to copy like this from a terminal window. Maybe Ctrl+ESC would be more appropriate?

history-view: simplify code and add clear option

---

src/parserfunc.c

Test:
```
$ CFLAGS="-ggdb3 -O0 -fsanitize=address" ./autogen.sh --prefix=/usr && make
$ ./src/test-mp-equation
```
master
```
SUMMARY: AddressSanitizer: 212469 byte(s) leaked in 2878 allocation(s).
```
PR
```
SUMMARY: AddressSanitizer: 212133 byte(s) leaked in 2875 allocation(s).
```

parserfunc: fix memory leak

---

src/test-mp-equation.c

Test:
```shell
$ CFLAGS="-ggdb3 -O0 -fsanitize=address" ./autogen.sh --prefix=/usr && make
$ ./src/test-mp-equation 
Passed all 445 tests
=================================================================
==72013==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 206176 byte(s) in 1516 object(s) allocated from:
#0 0x7f4fc6c6b6b7 in __interceptor_malloc (/lib64/libasan.so.6+0xb06b7)
#1 0x7f4fc673e8ed in __gmp_default_allocate (/lib64/libgmp.so.10+0x118ed)
Direct leak of 5745 byte(s) in 1305 object(s) allocated from:
#0 0x7f4fc6c6b6b7 in __interceptor_malloc (/lib64/libasan.so.6+0xb06b7)
#1 0x7f4fc68ac898 in g_malloc (/lib64/libglib-2.0.so.0+0x58898)
Direct leak of 64 byte(s) in 1 object(s) allocated from:
#0 0x7f4fc6c6b6b7 in __interceptor_malloc (/lib64/libasan.so.6+0xb06b7)
#1 …
```

test-mp-equation: Fix memory leak

---

src/mp.c
src/mp.h
src/parserfunc.c
src/test-mp-equation.c

Adds a new feature, the square and multiply algorithm, to calculate  `z = x^y mod p` really fast and correct. On the way I fixed a problem in `mp_modulus_divide` where calling it with equal arguments `z=x` like `mp_modulus_divide(x, p, x)` would not work. Inspired by gnome-calculators implementation (https://gitlab.gnome.org/GNOME/gnome-calculator/-/commit/5a4b32820877517eee1ebd6928a3a649f76aab2a).
Test:
Before PR:
`123^456mod78 = 0` (is wrong)
`123^456789mod10 = 0` (is wrong)
After PR:
`123^456mod78 = 27`
`123^456789mod10 = 3`
You can verify results with python console:
```
>>> pow(123,456,78)
27
```
You can even try very long numbers, like `123123123123123123123123123123123123123123123123123123123123^123123123123123123456789mod12312312312312312312312312312312312312312312312312310`
which …

add modular exponentiation ability and add acccording tests

---

configure.ac
src/Makefile.am

Test:
```shell
$ pkg-config --libs mpfr
-lmpfr -lgmp
```
Test 2:
```shell
$ ./autogen.sh --prefix=/usr && make V=1 &> make.log
$ grep lmpfr make.log
gcc  -g -O2   -o mate-calc mate-calc.o currency.o currency-manager.o math-buttons.o math-converter.o math-history.o math-history-entry.o math-display.o math-equation.o math-preferences.o math-variables.o math-variable-popup.o math-window.o mp.o mp-binary.o mp-convert.o mp-enums.o mp-equation.o mp-serializer.o mp-trigonometric.o financial.o unit.o unit-category.o unit-manager.o prelexer.o lexer.o parserfunc.o parser.o mate-calc-resources.o -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lmpfr -lgmp -lxml2 -Wl,--export-dynamic -lgmodule-2.0 -pthread -lglib-2.0 …
```

build: Remove redundant LDFLAGS

---

src/mate-calc.c
src/math-buttons.c
src/math-converter.c
src/math-variable-popup.c
src/mp-serializer.c

```
mate-calc.c:186:21: warning: declaration of ‘window’ shadows a global declaration [-Wshadow]
186 | quit_cb(MathWindow *window)
|         ~~~~~~~~~~~~^~~~~~
--
math-buttons.c:396:22: warning: declaration of ‘label’ shadows a previous local [-Wshadow]
396 |         const gchar *label;
|                      ^~~~~
--
math-converter.c:148:29: warning: declaration of ‘iter’ shadows a previous local [-Wshadow]
148 |                 GtkTreeIter iter;
|                             ^~~~
--
math-variable-popup.c:207:23: warning: declaration of ‘value’ shadows a parameter [-Wshadow]
207 |             MPNumber *value;
|                       ^~~~~
--
mp-serializer.c:162:22: warning: declaration of ‘digits’ shadows a previous local [-Wshadow]
162 |         const gchar *digits[] = {"₀", "₁", "₂", …
```

Remove -Wshadow warnings

---

src/mp-serializer.c

Simple fix for  #151. If real part of complex expression is 0, string was cleared and no zero was added if complex part also cancelled.

Fix empty string return for canceling complex expressions

---

src/math-equation.c

LeakSanitizer detected memory leaks:
```
Direct leak of 104 byte(s) in 1 object(s) allocated from:
#0 0x418c85 in __interceptor_calloc.part.0 (/usr/bin/mate-calc+0x418c85)
#1 0x7f587f9be9d0 in g_malloc0 (/lib64/libglib-2.0.so.0+0x589d0)
#2 0x44956e in math_equation_set_number /home/robert/sanitizer/mate-calc/src/math-equation.c:986:13
#3 0x44a04b in math_equation_look_for_answer /home/robert/sanitizer/mate-calc/src/math-equation.c:1307:9
#4 0x7f587f9b9350  (/lib64/libglib-2.0.so.0+0x53350)
```
Test:
```
CFLAGS="-fsanitize=leak -fno-omit-frame-pointer -g -ggdb3 -O0"
LDFLAGS="-fsanitize=leak -ggdb3"
CONF="--prefix=/usr"
$ CC="clang" CXX="clang++" CFLAGS="${CFLAGS}" ./autogen.sh ${CONF} && make
```

math-equation: Fix memory leak

---

help/C/keyboard.page
src/math-history-entry.c
src/math-history-entry.h
src/math-history.c
src/math-history.h
src/math-window.c

using alt+Up/Down, changed show history shortcut from` ctr+h` to `shift+ctrl+h` such that it does not interfere with hexadecimal shortcut `ctrl+h` when in programming mode and update keyboard shortcuts help page.
Similar to: https://gitlab.gnome.org/GNOME/gnome-calculator/-/commit/8417af309b59f8e5e575197fafad247c955337b5

Implemented navigation through history stack equations using keyboard

---

src/mp-convert.c

```
find . \( -name '*.h' -o -name '*.c' \) -exec sed -i 's/[[:space:]]*$//' {} \;
find . \( -name '*.h' -o -name '*.c' \) -exec sed -i 's/\t*$//' {} \;
```

mp-convert: Remove trailing spaces/tabs

---

src/unit-manager.c

The IAU changed the definition back in 2012 so that 1 au == 149 597 870 700 m exactly, the BIPM then followed in recognizing this value.
Ref:
https://www.nature.com/news/the-astronomical-unit-gets-fixed-1.11416 (doi:10.1038/nature.2012.11416)
https://www.bipm.org/utils/common/pdf/si-brochure/SI-Brochure-9.pdf (latest brochure, specifically Tableau 8)

Correct Astronomical unit (to 149597870700 m)

---

src/math-equation.c

fixes issue in programming mode:
> to reproduce:
> 256 * 256 * 256 * 256 * 256
> expected:
> 0000 0000 0000 0000 0000 0001 0000 0000
> 0000 0000 0000 0000 0000 0000 0000 0000
> actual:
> greys out
https://gitlab.gnome.org/GNOME/gnome-calculator/-/issues/38

Refresh bits panel after calculation

---

src/math-equation.c

fixes the issue:
> Press 7 and Enter. Screen should show 7 = 7, input field should show 7.
> Press left arrow and type 12, then the right arrow and type +7. Input field should show 127+7.
> Press Enter. Screen will show 127+7 = 91, input field will show 91
https://gitlab.gnome.org/GNOME/gnome-calculator/-/issues/59

Clear answer if editing right before it

---

src/math-buttons.c
src/math-equation.c

```
math-buttons.c:73: warning: macro "WM_HEIGHT_FACTOR" is not used [-Wunused-macros]
73 | #define WM_HEIGHT_FACTOR 30
--
math-buttons.c:72: warning: macro "WM_WIDTH_FACTOR" is not used [-Wunused-macros]
72 | #define WM_WIDTH_FACTOR  10
--
math-equation.c:52: warning: macro "MAX_DIGITS" is not used [-Wunused-macros]
52 | #define MAX_DIGITS 512
```

Remove unused macros

---

src/math-buttons.c

```
math-buttons.c:918:13: warning: format not a string literal, argument types not checked [-Wformat-nonliteral]
918 |             text = g_strdup_printf(format, i);
|             ^~~~
--
math-buttons.c:961:13: warning: format not a string literal, argument types not checked [-Wformat-nonliteral]
961 |             text = g_strdup_printf(format, i);
|             ^~~~
```

math-buttons: Remove warnings about format not a string literal

---

src/mate-calc-cmd.c
src/test-mp-equation.c
src/test-mp.c

test
```
$ make -C src check-TESTS
```
warnings
```
mate-calc-cmd.c:70:10: warning: unused parameter 'argc' [-Wunused-parameter]
mate-calc-cmd.c:70:23: warning: unused parameter 'argv' [-Wunused-parameter]
test-mp-equation.c:686:11: warning: unused parameter 'argc' [-Wunused-parameter]
test-mp-equation.c:686:24: warning: unused parameter 'argv' [-Wunused-parameter]
test-mp.c:224:11: warning: unused parameter 'argc' [-Wunused-parameter]
test-mp.c:224:24: warning: unused parameter 'argv' [-Wunused-parameter]
```

Remove warning about unused parameters in `ìnt main` function

---

configure.ac

```
$ ./autogen.sh --prefix=/usr
<cut>
Configure summary:
mate-calc 1.25.0
================
prefix:                       /usr
source code location:         .
compiler:                     gcc
compiler flags:               -g -O2
warning flags:                -Wall -Wmissing-prototypes
Now type `make' to compile mate-calc
```

build: add configure summary

---

src/math-equation.c

Test:
before:
<pre>
3871297301237120312 = 2^3 x 71 x 6.815664262741x10¹⁵ 
^----this is not a prime number (due to rounding)
</pre>
after:
<pre>
3871297301237120312 = 2^3 x 71 x 6815664262741409
^----better display it in fixed mode
</pre>

factorization: display prime factors in fixed number format

---

src/math-buttons.c
src/mp-serializer.c

I am not quite sure if you have to free the string returned by `g_locale_to_utf8`

fix memory leaks reported by valgrind

---

src/mp.c

The z value was set to 1, which is the same as the x value if both addresses x and z are equal. Thus, the final value of z was 1/1=1. Solved by making a temp variable.
No need to backport, because culprit b0117b1d5ae73916c6f0d289be1f693bb5f46824 is not in the 1.24 branch.

mp.c: mp_reciprocal: fix when calling it with same arguments.

---

src/mp-serializer.c

From the MPFR reference manual (https://www.mpfr.org/mpfr-current/#doc):
```
4.8 Getting the Best Efficiency Out of MPFR
Here are a few hints to get the best efficiency out of MPFR:
• you should avoid allocating and clearing variables. Reuse variables whenever possible, allo-
cate or clear outside of loops, pass temporary variables to subroutines instead of allocating
them inside the subroutines;
```

mp-serializer: init MPNumbers outside of loop

---

configure.ac

closes #192
Test:
```
$ ./autogen.sh --prefix=/usr
$ grep HAVE_LIBMPC config.h
#define HAVE_LIBMPC 1
$ grep "^LIBS =" Makefile
LIBS = -lmpc -lm 
$ make V=1 &> make.log
$ grep "\-lmpc" make.log
gcc  -g -O2   -o mate-calc mate-calc.o currency.o currency-manager.o math-buttons.o math-converter.o math-history.o math-history-entry.o math-display.o math-equation.o math-preferences.o math-variables.o math-variable-popup.o math-window.o mp.o mp-binary.o mp-convert.o mp-enums.o mp-equation.o mp-serializer.o mp-trigonometric.o financial.o unit.o unit-category.o unit-manager.o prelexer.o lexer.o parserfunc.o parser.o mate-calc-resources.o -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lmpfr -lgmp -lxml2 …
```

build: abort configuration when development library for MPC is missing

---

src/mp.h

Commit 869de6d8 changed the signatures of definitions of various mp_*
functions but did not update the declarations in mp.h to match.

Fix declaration/definition mismatches

---

src/math-buttons.c

Accessible names were previously copied from widget names, which are not localized.
(If this gets merged, the POT file should be updated as well.)

Accessibility: use localized button names for screen readers

---

.tx/config
.tx/config_20221024111755.bak

This is the result of running `tx migrate` in this repository. This is needed because the old client will be deprecated at the end of November, see https://docs.transifex.com/client/introduction. I plan to do this for all repositories.

tx: migrate config file

---

src/currency-manager.c

```
currency-manager.c: In function ‘load_ecb_rates’:
currency-manager.c:483:5: warning: implicit declaration of function ‘xmlInitParser’ [-Wimplicit-function-declaration]
483 |     xmlInitParser();
|     ^~~~~~~~~~~~~
currency-manager.c:485:16: warning: implicit declaration of function ‘xmlReadFile’ [-Wimplicit-function-declaration]
485 |     document = xmlReadFile(filename, NULL, 0);
|                ^~~~~~~~~~~
currency-manager.c:485:14: warning: assignment to ‘xmlDocPtr’ {aka ‘struct _xmlDoc *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
485 |     document = xmlReadFile(filename, NULL, 0);
|              ^
currency-manager.c:523:5: warning: implicit declaration of function ‘xmlCleanupParser’ [-Wimplicit-function-declaration]
523 |     xmlCleanupParser();
| …
```

Fix implicit function declarations with libxml2 2.12

---

src/math-display.c

Make the equation status the description of the equation entry as well so the screen reader can notify the user when it changes while the entry has focus.
Fixes #223.
(alternative to #224 that I like better)

a11y: Allow the screen reader to announce status changes
